# Mengaktifkan Fitur Bluetooth & Batere
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BATTERY_REPORTING=y

# Mengaktifkan Rotary Encoder
CONFIG_ZMK_EC11=y
CONFIG_ZN_EC11_TRIGGER_GLOBAL_THREAD=y

# Mengaktifkan Layar OLED (Jika Anda pakai)
CONFIG_ZMK_DISPLAY=y

# Catatan RGB Underglow / WS2812 pada nRF52840:
# Di ZMK, RGB underglow memakan konsumsi baterai yang sangat besar.
# Jika tetap ingin diaktifkan, hapus tanda pagar (#) di bawah ini:
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y